### ISSUE TITLE
Buble + Buba

### ISSUE THREAD

**Issue by davidchase** [mostjs/package-starter#101]
What do you guys think of switching to using Buble + Buba for this repo? It seems like we could gain from the bytes saved with Bublé and then instead of running `babel-node` or using `babel-register` we can use Buba for the tests.. just a thought

/cc @briancavalier @TylorS

**Comment by briancavalier** [comment]
👍 I could see this being a path to ES6 for mostjs core as well.

**Comment by davidchase** [comment]
i think we can close this issue?

**Comment by briancavalier** [comment]
Yep :)
